name: CI for IRIS Pipeline

on:
  push:
    branches: [main, dev]
  pull_request:
    branches: [main, dev]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2️⃣ Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      # 3️⃣ Setup CML
      - name: Setup CML
        uses: iterative/setup-cml@v2

      # 4️⃣ Cache pip dependencies
      - name: Cache pip dependencies
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/req.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 5️⃣ Install Python dependencies + DVC
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip setuptools wheel
          pip install --upgrade --use-deprecated=legacy-resolver -r req.txt
          # pip install "dvc[gcs]"  # install DVC with GCS support
          pip install dvc_gs

      # 6️⃣ Configure GCS authentication (if needed)
      - name: Pull data and models from DVC
        env:
         GOOGLE_APPLICATION_CREDENTIALS: ${{ github.workspace }}/gcp-key.json
        run: |
           echo "${{ secrets.GCP_KEY }}" > $GOOGLE_APPLICATION_CREDENTIALS
           pip install "dvc[gcs]"
           dvc pull -r myremote


      # # 7️⃣ Pull data and models from DVC
      # - name: Pull data and models from DVC
      #   run: |
      #     dvc pull -r myremote

      # 8️⃣ Run tests
      - name: Run tests
        run: pytest
